apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "airflow.fullname" . }}-logs
spec:
  capacity:
    storage: {{ .Values.airflow.logs.persistence.size | quote }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.{{ .Release.Namespace }}.svc.cluster.local
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "airflow.fullname" . }}-logs
  labels:
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.airflow.logs.persistence.size | quote }}
  {{- if .Values.airflow.logs.persistence.storageClass }}
  {{- if (eq "-" .Values.airflow.logs.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.airflow.logs.persistence.storageClass }}"
  {{- end }}
  {{- end }}
