apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "airflow.fullname" . }}-scheduler
  labels:
    app: {{ template "airflow.name" . }}-scheduler
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  #serviceAccountName: {{ template "airflow.fullname" . }}-cluster-access
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
        configmap.fabric8.io/update-on-change: "{{ template "airflow.fullname" . }}-env"
      labels:
        app: {{ template "airflow.name" . }}-scheduler
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "airflow.fullname" . }}-cluster-access
      securityContext:
        fsGroup: 1000
      restartPolicy: Always
      {{- if .Values.airflow.service_node_selector.key }}
      nodeSelector:
        {{ .Values.airflow.service_node_selector.key }}: {{ .Values.airflow.service_node_selector.value | quote }}
      {{- end }}
      containers:
      {{- if not .Values.airflow.dags.persistence.enabled }}
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.1.1
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 65533 # git-sync user
        volumeMounts:
          - name: {{ template "airflow.fullname" . }}-dags
            mountPath: /git
          {{- if or ( .Values.airflow.dags.git.sshKeyFile ) ( .Values.airflow.dags.git.knownHostsFile ) }}
          - name: git
            mountPath: /etc/git-secret
          {{- end }}
        env:
          #- name: GOOGLE_APPLICATION_CREDENTIALS
          #  value: /volumes/settings/google_app_creds.json
          - name: GIT_SYNC_REPO
            value: {{ .Values.airflow.dags.git.url }}
          - name: GIT_SYNC_BRANCH
            value: {{ .Values.airflow.dags.git.branch }}
          - name: GIT_SYNC_ROOT
            value: /git
          - name: GIT_SYNC_DEST
            value: repo
          {{- if .Values.airflow.dags.git.username }}
          - name: GIT_SYNC_USERNAME
            valueFrom:
              secretKeyRef:
                name: git
                key: GIT_SYNC_USERNAME
          {{- end }}
          {{- if .Values.airflow.dags.git.password }}
          - name: GIT_SYNC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: git
                key: GIT_SYNC_PASSWORD
          {{- end }}
          {{- if .Values.airflow.dags.git.sshKeyFile }}
          - name: GIT_SYNC_SSH
            value: "true"
          - name: GIT_SSH_KEY_FILE
            value: /etc/git-secret/ssh
          {{- end }}
          {{- if .Values.airflow.dags.git.knownHostsFile }}
          - name: GIT_KNOWN_HOSTS
            value: "true"
          - name: GIT_SSH_KNOWN_HOSTS_FILE
            value: /etc/git-secret/known_hosts
          {{- end }}
      {{- end }}
      - name: scheduler
        image: {{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
        imagePullPolicy: {{ .Values.airflow.image.pull_policy }}
        args: ["scheduler"]
        envFrom:
        - secretRef:
            name: {{ template "airflow.fullname" . }}-env
        env:
        - name: AIRFLOW_KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: airflow-config
          mountPath: /usr/local/airflow/airflow.cfg
          subPath: airflow.cfg
        - name: {{ template "airflow.fullname" . }}-dags
          mountPath: /usr/local/airflow/dags
        - name: airflow-logs
          mountPath: /usr/local/airflow/logs
      volumes:
      {{- if or ( .Values.airflow.dags.git.sshKeyFile ) ( .Values.airflow.dags.git.knownHostsFile ) }}
      - name: git
        secret:
          secretName: {{ template "airflow.fullname" . }}-git
          items:
          {{- if .Values.airflow.dags.git.sshKeyFile }}
          - key: gitSshKey
            path: ssh
            #defaultMode: 288 # 0400
            mode: 288 # 0400
          {{- end }}
          {{- if .Values.airflow.dags.git.knownHostsFile }}
          - key: known_hosts
            path: known_hosts
            #defaultMode: 288 # 0400
            mode: 288 # 0400
          {{- end }}
      {{- end }}
      - name: airflow-logs
        persistentVolumeClaim:
          claimName: {{ template "airflow.fullname" . }}-logs
      - name: airflow-config
        configMap:
          name: {{ template "airflow.fullname" . }}-config
      - name: {{ template "airflow.fullname" . }}-dags
        {{- if .Values.airflow.dags.persistence.enabled }}
        persistentVolumeClaim:
          {{- if .Values.airflow.dags.persistence.existingClaim }}
          claimName: "{{ .Values.airflow.dags.persistence.existingClaim }}"
          {{- else }}
          claimName: {{ template "airflow.fullname" . }}-dags
          {{- end }}
          readOnly: true
        {{- else }}
        emptyDir: {}
        {{- end }}
      securityContext:
        fsGroup: 65533 # to make SSH key readable