apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "airflow.fullname" . }}-web
  labels:
    app: {{ template "airflow.name" . }}-web
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    # Smooth rolling update of the Web UI
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ template "airflow.name" . }}-web
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
        configmap.fabric8.io/update-on-change: "{{ template "airflow.fullname" . }}-env"
      labels:
        app: {{ template "airflow.name" . }}-web
        release: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 1000
      restartPolicy: Always
      {{- if .Values.airflow.service_node_selector.key }}
      nodeSelector:
        {{ .Values.airflow.service_node_selector.key }}: {{ .Values.airflow.service_node_selector.value | quote }}
      {{- end }}
      initContainers:
      - name: "init-airflow"
        image: {{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
        imagePullPolicy: {{ .Values.airflow.image.pull_policy }}
        volumeMounts:
          - name: airflow-config
            mountPath: /usr/local/airflow/airflow.cfg
            subPath: airflow.cfg
          - name: init-airflow
            mountPath: /usr/local/init-airflow.sh
            subPath: init-airflow.sh
          #- name: airflow-gcs-creds
          #  mountPath: /volumes/settings
        envFrom:
          - secretRef:
              name: {{ template "airflow.fullname" . }}-env
        command:
          - "bash"
        args:
          - "-cx"
          - "bash /usr/local/init-airflow.sh"
      {{- if .Values.airflow.dags.persistence.enabled }}
      - name: "init-dags"
        image: {{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
        imagePullPolicy: {{ .Values.airflow.image.pull_policy }}
        volumeMounts:
          - name: {{ template "airflow.fullname" . }}-dags
            mountPath: /usr/local/airflow/dags
          - name: airflow-config
            mountPath: /usr/local/airflow/airflow.cfg
            subPath: airflow.cfg
          - name: init-dags
            mountPath: /usr/local/init-dags.sh
            subPath: init-dags.sh
          #- name: airflow-gcs-creds
          #  mountPath: /volumes/settings
        envFrom:
          - secretRef:
              name: {{ template "airflow.fullname" . }}-env
        command:
          - "bash"
        args:
          - "-cx"
          - "bash /usr/local/init-dags.sh"
      {{- end }}
      containers:
      {{- if not .Values.airflow.dags.persistence.enabled }}
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.1.1
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 65533 # git-sync user
        volumeMounts:
          - name: {{ template "airflow.fullname" . }}-dags
            mountPath: /git
          {{- if or ( .Values.airflow.dags.git.sshKeyFile ) ( .Values.airflow.dags.git.knownHostsFile ) }}
          - name: git
            mountPath: /etc/git-secret
          {{- end }}
        env:
          - name: GIT_SYNC_REPO
            value: {{ .Values.airflow.dags.git.url }}
          - name: GIT_SYNC_BRANCH
            value: {{ .Values.airflow.dags.git.branch }}
          - name: GIT_SYNC_ROOT
            value: /git
          - name: GIT_SYNC_DEST
            value: repo
          - name: GIT_SYNC_WAIT
            value: "{{ .Values.airflow.dags.git.wait }}"
          {{- if .Values.airflow.dags.git.username }}
          - name: GIT_SYNC_USERNAME
            valueFrom:
              secretKeyRef:
                name: git
                key: GIT_SYNC_USERNAME
          {{- end }}
          {{- if .Values.airflow.dags.git.password }}
          - name: GIT_SYNC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: git
                key: GIT_SYNC_PASSWORD
          {{- end }}
          {{- if .Values.airflow.dags.git.sshKeyFile }}
          - name: GIT_SYNC_SSH
            value: "true"
          - name: GIT_SSH_KEY_FILE
            value: /etc/git-secret/ssh
          {{- end }}
          {{- if .Values.airflow.dags.git.knownHostsFile }}
          - name: GIT_KNOWN_HOSTS
            value: "true"
          - name: GIT_SSH_KNOWN_HOSTS_FILE
            value: /etc/git-secret/known_hosts
          {{- end }}
      {{- end }}
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
          - name: nginx
            containerPort: 80
        volumeMounts:
          - name: nginx
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: nginx.conf
        readinessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
          httpGet:
            path: /health
            port: 80
        livenessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 5
          failureThreshold: 5
          httpGet:
            path: /health
            port: 80
      - name: webserver
        image: {{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
        imagePullPolicy: {{ .Values.airflow.image.pull_policy }}
        ports:
        - name: webserver
          containerPort: 8080
        args: ["webserver"]
        envFrom:
          - secretRef:
              name: {{ template "airflow.fullname" . }}-env
        env:
        #- name: GOOGLE_APPLICATION_CREDENTIALS
        #  value: /volumes/settings/google_app_creds.json
        - name: AIRFLOW_KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # - name: FORWARDED_ALLOW_IPS
        #   value: "*"
        volumeMounts:
        - name: airflow-config
          mountPath: /usr/local/airflow/airflow.cfg
          subPath: airflow.cfg
        #- name: airflow-gcs-creds
        #  mountPath: /volumes/settings
        - name: webserver-config
          mountPath: /usr/local/airflow/webserver_config.py
          subPath: webserver_config.py
        - name: airflow-logs
          mountPath: /usr/local/airflow/logs
        - name: {{ template "airflow.fullname" . }}-dags
          mountPath: /usr/local/airflow/dags
        readinessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 5
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
      volumes:
      - name: airflow-logs
        persistentVolumeClaim:
          claimName: {{ template "airflow.fullname" . }}-logs
      - name: airflow-config
        configMap:
          name: {{ template "airflow.fullname" . }}-config
      {{- if or ( .Values.airflow.dags.git.sshKeyFile ) ( .Values.airflow.dags.git.knownHostsFile ) }}
      - name: git
        secret:
          secretName: {{ template "airflow.fullname" . }}-git
          defaultMode: 288 # 0400
          items:
          {{- if .Values.airflow.dags.git.sshKeyFile }}
          - key: gitSshKey
            path: ssh
            #defaultMode: 288 # 0400
            mode: 288 # 0400
          {{- end }}
          {{- if .Values.airflow.dags.git.knownHostsFile }}
          - key: known_hosts
            path: known_hosts
            #defaultMode: 288 # 0400
            mode: 288 # 0400
          {{- end }}
      {{- end }}
      - name: webserver-config
        secret:
          secretName: webserver-config
      - name: init-airflow
        configMap:
          name: {{ template "airflow.fullname" . }}-init
      - name: nginx
        configMap:
          name: {{ template "airflow.fullname" . }}-nginx
      {{- if .Values.airflow.dags.persistence.enabled }}
      - name: init-dags
        configMap:
          name: {{ template "airflow.fullname" . }}-init-dags
      {{- end }}
      - name: {{ template "airflow.fullname" . }}-dags
        {{- if .Values.airflow.dags.persistence.enabled }}
        persistentVolumeClaim:
          {{- if .Values.airflow.dags.persistence.existingClaim }}
          claimName: "{{ .Values.airflow.dags.persistence.existingClaim }}"
          {{- else }}
          claimName: {{ template "airflow.fullname" . }}-dags
          {{- end }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      securityContext:
        fsGroup: 65533 # to make SSH key readable
